name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v6
        with:
          args: --ignore-platform-reqs

      - name: PHP 8.0
        uses: php-actions/phpunit@v3
        with:
          version: 10
          php_version: 8.0

      - name: PHP 8.1
        uses: php-actions/phpunit@v3
        with:
          version: 10
          php_version: 8.1

      - name: PHP 8.2
        uses: php-actions/phpunit@v3
        with:
          version: 10
          php_version: 8.2
